#!/bin/bash
##! @description: usage
##! @version: 1
##! @author: Menglong TAN <tanmenglong@gmail.com>
##! @date:   Mon Dec  8 12:29:25 2014

bin=`which $0`
bin=`dirname ${bin}`
bin=`cd "$bin"; pwd`

"$bin"/hpipe $@
